### ISSUE TITLE
Error when trying to run apy command

### ISSUE THREAD

**Issue by skervim** [lervag/apy#1]
I installed `apy` with 
`pip install -e .`
The command `apy --help` works fine, but when I try to do e.g. `apy add`, I get:

```
Traceback (most recent call last):
  File "/home/skervim/anaconda3/envs/rl/bin/apy", line 11, in <module>
    load_entry_point('apy', 'console_scripts', 'apy')()
  File "/home/skervim/anaconda3/envs/rl/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/skervim/anaconda3/envs/rl/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/skervim/anaconda3/envs/rl/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/skervim/anaconda3/envs/rl/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/skervim/anaconda3/envs/rl/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/skervim/apy/apy/cli.py", line 57, in add
    with Anki(BASE) as a:
  File "/home/skervim/apy/apy/anki.py", line 14, in __init__
    import anki
ModuleNotFoundError: No module named 'anki'
```

**Comment by skervim** [comment]
Thank you for the nice answer! 

I actually have anki desktop already installed. I had followed the instructions at https://apps.ankiweb.net/#linux (I'm using ubuntu 18.04).

**Comment by lervag** [comment]
What's the output of `which anki`; and whats the output of `head /path/to/anki` (where the path should be provided by `which`)? E.g., for me:

```
> which anki
/usr/bin/anki

> head /usr/bin/anki
#!/usr/bin/env python3

import sys
sys.path.append("/usr/share/anki")

import aqt
aqt.run()
```

I'm most interested in the content of the `sys.path.append` line. If it is different from mine, then that might explain the problem.

**Comment by skervim** [comment]
```
> which anki
/usr/local/bin/anki
```
```
> head /usr/local/bin/anki
This is a binary file in my case
```

**Comment by lervag** [comment]
Yes, I think this might explain the issue. When you download from the Anki web page, you only get a bundled/compiled version. The source is not available. Could you uninstall Anki with `cd Downloads/anki-2.1.15-linux-amd64` then `sudo make uninstall`, then do `sudo apt install anki`? I think this might fix your issue.

I see I will need to update the README/instructions again, but I'll wait until we've settled this so that I know things work as expected.

**Comment by skervim** [comment]
Your proposed solution, i.e., installing Anki with `sudo apt install anki`, worked to solve the above problem. However, a series of problems followed: 

I needed to install `pyaudio`, which I did with 
```
sudo apt-get install portaudio19-dev python-pyaudio
pip install pyaudio
```
(A simple `pip install pyaudio` is not sufficient on ubuntu 18.04, see [here](https://ourcodeworld.com/articles/read/974/how-to-solve-installation-error-of-pyaudio-in-ubuntu-18-04-fatal-error-portaudio-h-file-not-found) 

Then the following problem occured: 
```
ModuleNotFoundError: No module named 'sip'
```
which I could only solve by changing 
```
import sip
```
to
```
try:
    import sip
except ImportError:
    from PyQt5 import sip
```
in the beginning of the file `/usr/share/anki/aqt/qt.py`. 

The next error was: 
```
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
```
which could be solved by a simple `pip install PyQtWebEngine`.

Next, I needed to solve `NameError: name 'QWebEngineView' is not defined
` by adding the import statement `from PyQt5.QtWebEngineWidgets import *` to the file `/usr/share/anki/aqt/webview.py` as explained [here](https://askubuntu.com/a/1150608).

Then installing beautifulsoup, requests and send2trash:
```
pip install bs4
pip install requests
pip install send2trash
``` 
Finally, I get the following problem:
```
AttributeError: 'ProfileManager' object has no attribute 'setupMeta'
```
I think this is not solvable since the `setupMeta` apparently has been added quite recently
https://github.com/dae/anki/commit/f2b5c8a8624912cae677674f2a1bc186e6694061
and does not exist in the old distributed version (Version 2.1.0beta36
Qt 5.9.5 PyQt 5.10.1)

Having reached this point, I think trying to make `apy` work with the distributed version of anki on ubuntu 18.04 is not the way to go. 

Anki's installation guide also notes: 

> Some Linux distributions include Anki in their repositories. We've seen many users experience problems with these distributed versions, due to them being out of date or missing appropriate libraries. For this reason, the compiled package above is recommended over using the version of Anki bundled with your Linux distribution.

This brings me to the following question, how did you make it work? :D

**Comment by lervag** [comment]
First, thanks for taking the time to go through all these hoops, it is really appreciated!

> This brings me to the following question, how did you make it work? :D

Well, I'm on Arch Linux. For me, doing `pacman -S anki` just works. It installs Anki desktop so that it works as expected, and it includes the sources which are put at `/usr/share/anki`.

> I guess the only thing I'm missing now is to what do I set:
> `export APY_ANKI_PATH=/my/path/to/anki`?

Ok, so, here is what I expect should work (you already did part of it):

```sh
# Decide on a desired path, e.g. $HOME/anki (but it can be whatever you want):
cd $HOME
git clone -b 2.1.15 https://github.com/dae/anki.git
cd anki

# Extra steps if you want to test everything in a virtualenv
python -m venv .venv
source .venv/bin/activate
pip install --upgrade pip setuptools > /dev/null

# Install dependencies
pip install -r requirements.txt

# Build the UI forms
./tools/build_ui.sh

# Fetch and install apy
cd $HOME
git clone https://github.com/lervag/apy
cd apy
pip install -e .

export APY_ANKI_PATH=$HOME/anki
apy info
```

Note that you can do `pip install --user -e .` to install user local (then you need to update your `PATH` to include the local pip installed binaries).

If you are generally happy with how Anki desktop works for you the way you previously installed, then I propose that you just keep the github-fetched version for making `apy` work. That is, don't proceed to install Anki from the github source, only prepare the sources as outlined above.

I hope this helps!

**Comment by skervim** [comment]
Thank you very much! It works! 
The only missing step was indeed: `export APY_ANKI_PATH=$HOME/anki`. 
(Before I had unsuccesfully tried `export APY_ANKI_PATH=~/anki`) 
Looking forward to try out `apy` and report/help back in the future!

**Comment by lervag** [comment]
> Thank you very much! It works!

Great, I'm very happy to hear it!

>  Looking forward to try out apy and report/help back in the future!

I will very much appreciate input and help in any way possible. For me, things work very well now, and apy is a crucial part of my Anki workflow. However, I'm sure there are a lot of stuff that can be improved, and that there are features that I haven't thought of yet. So I'm looking forward to hearing from you!

**Comment by jcrben** [comment]
I managed to set this up using 2.1.6 on mac. A couple things to note for anyone who comes later:
* I wouldn't bother with 2.1.5 - it requires pyqt5==5.9 but the 5.9 compatible pyqtwebengine seems to be dropped. Skip to 2.1.6 or higher instead and do `pip install pyqt5==5.12`.
* I did not need some of the other workarounds, but did still need to add `from PyQt5.QtWebEngineWidgets import *`
* I got up hung up a bit because instead of `export APY_ANKI_PATH` I just tried to just define it locally with `APY_ANKI_PATH=<path> apy`, but that doesn't work since python is using os.environ to look it up.

**Comment by lervag** [comment]
> using 2.1.6 

Referring to the Anki version? Did you try any later versions? I'm on 2.1.15...

>  did not need some of the other workarounds

I'm not quite sure exactly what you are talking of.

> I got up hung up a bit because instead of export APY_ANKI_PATH I just tried to just define it locally with APY_ANKI_PATH=<path> apy, but that doesn't work since python is using os.environ to look it up.

That's strange. I would expect `os.environ` to respond well to `ENV=value python-script`.

In any case: It would be very good if you would be willing to submit a PR with a short description of the steps you used to make this work on a mac! You could add it to the README file under install instructions.

**Comment by jcrben** [comment]
Yes, 2.1.6 is the checked out tag and version of Anki. As far as I can tell 2.1.5 is not gonna work unless you install a compatible pyqtwebengine without pip.

Workarounds are described at https://github.com/lervag/apy/issues/1#issuecomment-543666794

> That's strange. I would expect os.environ to respond well to ENV=value python-script

I think maybe I messed up and didn't do it in the same command, tho didn't realize that mattered either.

I might add instructions if I do this again.

**Comment by lervag** [comment]
> Yes, 2.1.6 is the checked out tag and version of Anki. As far as I can tell 2.1.5 is not gonna work unless you install a compatible pyqtwebengine without pip.

The most recent version of Anki is 2.1.17. I'm on 2.1.15. Version 2.1.6 was [released december 2018](https://github.com/ankitects/anki/releases). This is why I'm asking, because it seems strange that you are discussing these old versions.

> I think maybe I messed up and didn't do it in the same command (line), tho didn't realize that mattered either since it was in the same shell.

In Bash shells (and similar shells) you need to either prepend `ENV=val` to the command for the variable to be defined in the environment, or to explicitly `export` it. So, two examples based on how to use `apy`:

```sh
# Explicit export. This makes the `APY_ANKI_PATH` available for the
# following commands.
export APY_ANKI_PATH=$HOME/anki
apy info

# Implicit "export", which makes `APY_ANKI_PATH` available for the "current"
# command.
APY_ANKI_PATH=$HOME/anki apy info
```

**Comment by jcrben** [comment]
Sorry, typo - I meant 2.1.16 and 2.1.15!

**Comment by lervag** [comment]
Great, then that's settled. So, if you do get the time, I'd be happy to consider a PR with some install instructions for macos.

**Comment by pietro14** [comment]
I am having the same problem, but I am not able to solve it, even with `APY_ANKI_PATH=$HOME/anki`:

```
Traceback (most recent call last):
  File "/home/pietro/.local/bin/apy", line 33, in <module>
    sys.exit(load_entry_point('apy', 'console_scripts', 'apy')())
  File "/home/pietro/.local/bin/apy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pietro/git/apy/apy/cli.py", line 8, in <module>
    from apy.anki import Anki
  File "/home/pietro/git/apy/apy/anki.py", line 7, in <module>
    import anki
ModuleNotFoundError: No module named 'anki'
```

I installed Anki from the official web site https://apps.ankiweb.net/ (anki-2.1.55-linux-qt6)

I cloned the git repo of `apy` and installed it with `pip install -e .`

I also cloned the Anki repo in $HOME/git/ (where I keep all my cloned repos form github). And I run `APY_ANKI_PATH=$HOME/git/anki` 

The result is the error above, when I try to run `apy info`

Could you help me? Thanks

**Comment by lervag** [comment]
> I am having the same problem, but I am not able to solve it, even with `APY_ANKI_PATH=$HOME/anki`: …
> 
> Could you help me? Thanks

I'd be glad to help you. Could I kindly ask you to open a new issue and describe it independent of the present thread? As you may notice, the current thread was resolved almost three years ago, so there have been updates and changes since then that may make some of the comments here outdated.

I believe the issue is about how you install Anki. Still, it would be easier to help if you open a new issue and include as many details as you can. More or less the same as in your last comment, but also please mention your OS (and distribution, if applicable). Feel free to link to this issue, since you believe they are related.
