### ISSUE TITLE
Bug: adding zero notes causes crash

### ISSUE THREAD

**Issue by ckp95** [lervag/apy#18]
If you run `apy add` but change your mind and don't add anything (e.g. straight away pressing `:wq` in Vim or `Ctrl-X` in Nano), it crashes:

```
[ckp95@ckp95-laptop anki]$ apy add
reverting to stock json
Dupe detected, note was not added!
Question:

Traceback (most recent call last):
  File "/home/ckp95/.local/bin/apy", line 8, in <module>
    sys.exit(main())
  File "/home/ckp95/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ckp95/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ckp95/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ckp95/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ckp95/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ckp95/.local/lib/python3.8/site-packages/apy/cli.py", line 75, in add
    click.echo(f'Added note to deck: {decks[0]}')
IndexError: list index out of range
```

**Comment by lervag** [comment]
Ah, yes. If you were to quit with `:cquit` in Vim, this would work as expected. But I think apy does not properly handle if the notes are not parseable (e.g. if you try to add an empty note, as in this case). I'll fix it. I guess the most natural behaviour would be to issue a warning when a note was not successfully parsed, and then avoid the error.

**Comment by lervag** [comment]
Ok, I can't quite reproduce this, actually. I think the issue is something else. Not sure exactly how to fix this unlless I can reproduce it, sorry.

Note: You should clean up such notes with e.g. `apy review -q added:1` or the Anki browser and delete them, as it seems you might have actually added notes this way.

**Comment by ckp95** [comment]
I upgraded to the newer version (checked with `--version`) and the same thing is happening.

**Comment by ckp95** [comment]
>Ok, I can't quite reproduce this, actually. I think the issue is something else. Not sure exactly how to fix this unlless I can reproduce it, sorry.

Have a look at my [`cli-tests` branch](https://github.com/ckp95/apy/commit/b856fa0d99e0944cb52ca80c4ab17aa0b29ecb8c), the test case `test_cli_add_from_file` reproduces it for me. I tested using the CLI interface itself because I couldn't reproduce it in the same way as the current test cases are written. Does this show the problem on your end?

(oh and you'll need to run `pytest --ignore=tests/test_decks.py` because that branch doesn't have [this change](https://github.com/lervag/apy/pull/21) in it)

**Comment by lervag** [comment]
Thanks! I've copied your cli tests! I was not aware of the `click.testing` module and I very much like the use of the temporary directories for testing as you've done here. Again, thanks!

Also, I can now reproduce the error and I'll look into a way to fix it!

**Comment by ckp95** [comment]
Adding this bit to `add` and `add_from_file` seemed to work:

```
diff --git a/apy/cli.py b/apy/cli.py
index d6dfcf0..221bc5e 100644
--- a/apy/cli.py
+++ b/apy/cli.py
@@ -76,6 +76,10 @@ def add(tags, model, deck):
         decks = [a.col.decks.name(c.did) for n in notes for c in n.n.cards()]
         n_notes = len(notes)
         n_decks = len(decks)
+        
+        if n_decks == 0:
+            click.echo("No notes added")
+            return None
 
         if a.n_decks > 1:
             if n_notes == 1:
@@ -108,6 +112,10 @@ def add_from_file(file, tags):
         n_notes = len(notes)
         n_decks = len(decks)
 
+        if n_decks == 0:
+            click.echo("No notes added")
+            return None
+
         if a.n_decks > 1:
             if n_notes == 1:
                 click.echo(f'Added note to deck: {decks[0]}')
```

**Comment by lervag** [comment]
Thanks! I added a similar check for the `n_notes` attribute. In principle, I think there might still be a slight bug here, since the `empty.md` note is still parsed and we try to add it. It is detected as a dupe and so no notes are actually added.

In any case, I think the point here is not to become perfect. Good is good enough. When I make mistakes, I have found I can still use apy to fix them quite easily with the `apy review` function.

I really appreciate your effort, it is very nice to get some help in fixing issues and improving this utility. `apy` is already at 95% fully functional for me, but it might have some rough edges especially with regard to other users workflows and similar. As such, it is very nice to get help in fixing these.
