### ISSUE TITLE
Annoyance: apy add leaves markdown files littering the directory

### ISSUE THREAD

**Issue by ckp95** [lervag/apy#19]
If you run `apy add` and add some notes interactively, the directory is left with a .md file containing those notes. I think it would be better that they be deleted afterwards by default, or else saved in the /tmp directory.

```
[ckp95@ckp95-laptop anki]$ ls
[ckp95@ckp95-laptop anki]$ apy add
reverting to stock json
Added note to deck: All
Review added notes? [y/N]: n
Database was modified.
Remember to sync!
[ckp95@ckp95-laptop anki]$ ls
note_4akr_cca.md
```

**Comment by lervag** [comment]
Yes, I agree. The reason is that in the beginning, I was afraid to delete the files because I was not sure how robust this thing would be. And now I mainly write my notes first in a notes.md file, then add them with `apy add-from-file`. I think that the best solution is to save the notes in `/tmp/note_xxxx_.md` and not delete the files after. Agreed?

**Comment by ckp95** [comment]
Yeah the /tmp solution seems the most sensible.

**Comment by lervag** [comment]
I'll push a new version tag later. But I'm curious, do you get the fix to this with the way you install, or are you stuck on the 0.4 tag?

**Comment by ckp95** [comment]
Yeah it's fixed now, thanks!

**Comment by lervag** [comment]
Great, happy to hear it!
