### ISSUE TITLE
`<u>` not interpreted in the editor

### ISSUE THREAD

**Issue by AdrienLemaire** [lervag/apy#28]
Not sure if it's a bug or feature request.

I just created a new card (seems to work well, that's awesome!)
![](https://i.imgur.com/3RwIoUd.png)

And I noticed that all `<b>` tags got converted and the inner word made bold (like `<b>curriculum</b>`.
But `<u>` tags are not converted. 

Is the boldening process made on your side in the editor, or should I be looking elsewhere (zsh, alacritty) for that ?

Thanks for the support!

**Comment by lervag** [comment]
> Not sure if it's a bug or feature request.
> 
> I just created a new card (seems to work well, that's awesome!)
> ![](https://camo.githubusercontent.com/9fb6218274e7cbe99eba16e1afbf314c11923464/68747470733a2f2f692e696d6775722e636f6d2f335277496f55642e706e67)
> 
> And I noticed that all `<b>` tags got converted and the inner word made bold (like `<b>curriculum</b>`.
> But `<u>` tags are not converted.
> 
> Is the boldening process made on your side in the editor, or should I be looking elsewhere (zsh, alacritty) for that ?
> 
> Thanks for the support!

**Comment by lervag** [comment]
> I just created a new card (seems to work well, that's awesome!)

Yes, I agree! I now make all of my new cards with apy. :)

> And I noticed that all `<b>` tags got converted and the inner word made bold (like `<b>curriculum</b>`.
> But `<u>` tags are not converted.
> 
> Is the boldening process made on your side in the editor, or should I be looking elsewhere (zsh, alacritty) for that ?

Yes, I've made a simple converter that parses the html for better printing in a terminal. You can use the `p` command to see the actual html (although it is "prettified").

I realize today that I should have avoided writing this code myself, because there are better packages available that could do it for me, but I've not found the time to simplify/improve on this point yet. The code that prints the notes is a little bit "messy", so it is not so straightforward, unfortunately. So, I've sort of landed on "if it ain't broke, don't fix it".

I'm pushing an update to support the `<u>...</u>` tag now. I've also tried to handle italized text better.

> Thanks for the support!

My pleasure. And thanks for opening issues, I appreciate the feedback and suggestions for improvements/features!

**Comment by lervag** [comment]
I assume we can close this?

**Comment by AdrienLemaire** [comment]
Didn't even notice that it was done, thanks!
