### ISSUE TITLE
Diff html to update markdown notes

### ISSUE THREAD

**Issue by AdrienLemaire** [lervag/apy#36]
While answering https://github.com/lervag/dotvim/issues/2#issuecomment-695209214 about wiki.vim, I got an idea to resolve my pain point described in #32 and let me use markdown-only notes editable from my phone.

**Would it be possible to diff the data-original-markdown content with the html content and sync the markdown accordingly?**

----

Here's an example:

1. Write a markdown card
    ```markdown
    What is the **caiptal of France**? 
    ```
2. It gets synced to anki as
    ```html 
    <div data-original-markdown="AB...YZ">
        What is the <b>caiptal of France</b>?
    </div>
    ```
3. From the phone, fix the typo (since the markdown plugin isn't available, the data-original-markdown attribute is not being updated)
    ```html 
    <div data-original-markdown="AB...YZ">
        What is the <b>capital of France</b>?
    </div>
    ```
4. Syncing back to apy, first extract the data-original-markdown data and re-convert to html, then diff the output
    ```diff
    <div data-original-markdown="AB...YZ">
    -    What is the <b>caiptal of France</b>?
    +    What is the <b>capital of France</b>?
    </div>
    ```
5. Update the markdown card (I suppose that's the hardest part... maybe just extract the differing words with a tool like `cmp`, and do a find-and-replace operation ?)
    ```markdown
    What is the **capital of France**? 
    ```
6. Syncing back to anki, the data-original-markdown content is updated
    ```html 
    <div data-original-markdown="CD...WX">
        What is the <b>capital of France</b>?
    </div>
    ```

When I say "Syncing back to apy", I'm just not sure when apy re-extract the markdown from data-original-markdown. If it's on a `apy list` & co, then doing this operation on a `apy review` + `e` could be the least expensive operation.

**Comment by lervag** [comment]
> **Would it be possible to diff the data-original-markdown content with the html content and sync the markdown accordingly?**

That's an interesting idea! My initial thought is to simplify things. How about this:

1. Write a markdown card (below) and sync to Anki.
   ```gfm
   What is the **caiptal of France**?
   ```

2. From the phone, fix the typo (as below), then sync again.
   ```html
   <div data-original-markdown="AB...YZ">
       What is the <b>capital of France</b>?
   </div>
   ```

4. Now, when we edit or display the card with apy, we first compare the html produced by the markdown given by `data-original-markdown` and the actual html content. By "definition", this should be identical. If it is not, then it implies that the html has been externally modified. Thus we could give a warning that explains that the content is inconsistent. When we edit the content, it should show both the original markdown and the updated html (perhaps converted back to markdown?) so that we can choose what to use.

So, essentially, my suggestion is to add a check for consistency between markdown and the plain html. Cards with inconsistent fields will be displayed alongside a warning and suggestion to update the note (with `apy review`).

What do you think?

**Comment by AdrienLemaire** [comment]
@lervag check for consistency with warning showing the difference and leaving it to the user to fix the card sounds great! Thanks for considering it!

**Comment by lervag** [comment]
It's been a year, so about time to push an update. Sorry about the lack of progress, but I've been too busy with a lot of other things. However, I believe this feature is added now. If you still use Anki and still use apy, I'd be happy to get some feedback.
