### ISSUE TITLE
unexpected keyword argument `for_deck`

### ISSUE THREAD

**Issue by danjenson** [lervag/apy#44]
Using the example shown [here](https://github.com/lervag/apy/wiki/Vim) under number 3, I get:
![image](https://user-images.githubusercontent.com/4793438/151054127-d6a4fc62-559a-4223-bb41-582170fc819e.png)
My `~/.config/apy/apy.json`:
```json
{
  "base": "/home/danj/.local/share/Anki2/",
  "profile": "danj",
  "query": "tag:leech",
  "presets": {
    "default": { "model": "Custom", "tags": ["marked"] }
  },
  "pngCommands": [
    ["latex", "-interaction=nonstopmode", "tmp.tex"],
    [
      "dvipng",
      "-D",
      "150",
      "-T",
      "tight",
      "-bg",
      "Transparent",
      "tmp.dvi",
      "-o",
      "tmp.png"
    ]
  ],
  "svgCommands": [
    ["lualatex", "-interaction=nonstopmode", "tmp.tex"],
    ["pdfcrop", "tmp.pdf", "tmp.pdf"],
    ["pdf2svg", "tmp.pdf", "tmp.svg"]
  ]
}

```

apy 0.9.0
anki 2.1.15
void linux 5.15.16_1

**Comment by lervag** [comment]
apy v0.9 is not compatible with anki 2.1.15. Sorry. See the README under the changelog section - v0.9 is compatible with Anki 2.1.49. I believe your issue should be resolved if you update Anki to this version.

The reason is that `apy` relies on the python backend of Anki itself, and this changes with the updates of Anki. So, in Anki 2.1.49, the `ModelManager` class is different from the corresponding class in version 2.1.15.

**Comment by danjenson** [comment]
Ok, thanks! sorry about that, submitting a PR to the void package maintainers
